# Generated by Django 2.1.1 on 2019-03-29 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sunscreen', '0002_auto_20190329_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='sunscreen.UserProfile'),
        ),
    ]
